name: social_media
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:

  sdk: '>=2.18.4 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  either_dart: ^0.3.0
  english_words: ^4.0.0
  equatable: ^2.0.5
  favorite_button: ^0.0.4
  firebase_core: ^2.7.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_localizations:
    sdk: flutter
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.6.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  get: ^4.6.5
  google_mobile_ads: ^2.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.5
  mysql1: ^0.20.0
  provider: ^6.0.5
  rename: ^2.0.1
  responsive_framework: ^0.1.4
  shared_preferences: ^2.0.17
  sqflite: ^2.2.6
  upgrader: null
  url_launcher: ^6.0.9
  webview_flutter: ^4.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  images_path: "appIconPath"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    images_path: "appIconPath"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    images_path: "appIconPath"
    icon_size: 48 # min:48, max:256, default: 48flutter:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/images/websites_images/
    - assets/images/another/
    - assets/images/websites_images/programing/
    - assets/images/websites_images/soshal/
    - assets/images/websites_images/news/
    - assets/images/websites_images/sport/
    - assets/images/websites_images/islami/
    - assets/images/websites_images/freelancer/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700
